before_install:
- source install-jdk.sh --feature ea

install:
- ./build.jsh
- ARTIFACTS="target/build/artifacts"
- JARS="-Dfile=$ARTIFACTS/bach.jar -Dsources=$ARTIFACTS/bach-sources.jar -Djavadoc=$ARTIFACTS/bach-javadoc.jar"
- find $ARTIFACTS
- mvn install:install-file $JARS -DgroupId=$GROUP -DartifactId=bach -Dversion=$VERSION -Dpackaging=jar -DgeneratePom=true
