#!/usr/bin/env bash

if [[ $1 == 'boot' ]]; then
  jshell --module-path .bach/cache --add-modules com.github.sormuras.bach .bach/boot.jsh
else
  java --module-path .bach/cache --module com.github.sormuras.bach "$@"
fi
