#!/usr/bin/env sh ${JAVA_HOME}/bin/java --source 15

public class bach {
  public static void main(String... args) {
    System.out.println("Bach Launcher");
    System.out.println("  args: [" + String.join(", ", args) + "]");
  }
}
