/*
 * Bach - Java Shell Builder
 * Copyright (C) 2020 Christian Stein
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.sormuras.bach.internal;

import java.util.Locale;
import java.util.TreeMap;

/** Mutable map of module names to mostly Maven-based coordinate mappings. */
public /*static*/ class ModulesMap extends TreeMap<String, String> {
  private static final long serialVersionUID = -7978021121082640440L;

  public static String platform(String linux, String mac, String windows) {
    var os = System.getProperty("os.name").toLowerCase(Locale.ENGLISH);
    return os.contains("win") ? windows : os.contains("mac") ? mac : linux;
  }

  public ModulesMap() {
    put(
        "javafx.base",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/14.0.1/javafx-base-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/14.0.1/javafx-base-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-base/14.0.1/javafx-base-14.0.1-win.jar"));
    put(
        "javafx.controls",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-controls/14.0.1/javafx-controls-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-controls/14.0.1/javafx-controls-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-controls/14.0.1/javafx-controls-14.0.1-win.jar"));
    put(
        "javafx.fxml",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/14.0.1/javafx-fxml-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/14.0.1/javafx-fxml-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-fxml/14.0.1/javafx-fxml-14.0.1-win.jar"));
    put(
        "javafx.graphics",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-graphics/14.0.1/javafx-graphics-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-graphics/14.0.1/javafx-graphics-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-graphics/14.0.1/javafx-graphics-14.0.1-win.jar"));
    put(
        "javafx.media",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-media/14.0.1/javafx-media-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-media/14.0.1/javafx-media-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-media/14.0.1/javafx-media-14.0.1-win.jar"));
    put(
        "javafx.swing",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-swing/14.0.1/javafx-swing-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-swing/14.0.1/javafx-swing-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-swing/14.0.1/javafx-swing-14.0.1-win.jar"));
    put(
        "javafx.web",
        platform(
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/14.0.1/javafx-web-14.0.1-linux.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/14.0.1/javafx-web-14.0.1-mac.jar",
            "https://repo.maven.apache.org/maven2/org/openjfx/javafx-web/14.0.1/javafx-web-14.0.1-win.jar"));
    put("junit", "https://repo.maven.apache.org/maven2/junit/junit/4.13/junit-4.13.jar");
    put(
        "net.bytebuddy",
        "https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.10.10/byte-buddy-1.10.10.jar");
    put(
        "net.bytebuddy.agent",
        "https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy-agent/1.10.10/byte-buddy-agent-1.10.10.jar");
    put(
        "org.apiguardian.api",
        "https://repo.maven.apache.org/maven2/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar");
    put(
        "org.assertj.core",
        "https://repo.maven.apache.org/maven2/org/assertj/assertj-core/3.16.1/assertj-core-3.16.1.jar");
    put(
        "org.hamcrest",
        "https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest/2.2/hamcrest-2.2.jar");
    put(
        "org.junit.jupiter",
        "https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter/5.7.0-M1/junit-jupiter-5.7.0-M1.jar");
    put(
        "org.junit.jupiter.api",
        "https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-api/5.7.0-M1/junit-jupiter-api-5.7.0-M1.jar");
    put(
        "org.junit.jupiter.engine",
        "https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.7.0-M1/junit-jupiter-engine-5.7.0-M1.jar");
    put(
        "org.junit.jupiter.params",
        "https://repo.maven.apache.org/maven2/org/junit/jupiter/junit-jupiter-params/5.7.0-M1/junit-jupiter-params-5.7.0-M1.jar");
    put(
        "org.junit.platform.commons",
        "https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-commons/1.7.0-M1/junit-platform-commons-1.7.0-M1.jar");
    put(
        "org.junit.platform.console",
        "https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-console/1.7.0-M1/junit-platform-console-1.7.0-M1.jar");
    put(
        "org.junit.platform.engine",
        "https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-engine/1.7.0-M1/junit-platform-engine-1.7.0-M1.jar");
    put(
        "org.junit.platform.launcher",
        "https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-launcher/1.7.0-M1/junit-platform-launcher-1.7.0-M1.jar");
    put(
        "org.junit.platform.reporting",
        "https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-reporting/1.7.0-M1/junit-platform-reporting-1.7.0-M1.jar");
    put(
        "org.junit.platform.testkit",
        "https://repo.maven.apache.org/maven2/org/junit/platform/junit-platform-testkit/1.7.0-M1/junit-platform-testkit-1.7.0-M1.jar");
    put(
        "org.junit.vintage.engine",
        "https://repo.maven.apache.org/maven2/org/junit/vintage/junit-vintage-engine/5.7.0-M1/junit-vintage-engine-5.7.0-M1.jar");
    put("org.lwjgl", "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3.jar");
    put(
        "org.lwjgl.assimp",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-assimp/3.2.3/lwjgl-assimp-3.2.3.jar");
    put(
        "org.lwjgl.assimp.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-assimp/3.2.3/lwjgl-assimp-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-assimp/3.2.3/lwjgl-assimp-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-assimp/3.2.3/lwjgl-assimp-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.bgfx",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-bgfx/3.2.3/lwjgl-bgfx-3.2.3.jar");
    put(
        "org.lwjgl.bgfx.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-bgfx/3.2.3/lwjgl-bgfx-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-bgfx/3.2.3/lwjgl-bgfx-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-bgfx/3.2.3/lwjgl-bgfx-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.cuda",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-cuda/3.2.3/lwjgl-cuda-3.2.3.jar");
    put(
        "org.lwjgl.egl",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-egl/3.2.3/lwjgl-egl-3.2.3.jar");
    put(
        "org.lwjgl.glfw",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-glfw/3.2.3/lwjgl-glfw-3.2.3.jar");
    put(
        "org.lwjgl.glfw.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-glfw/3.2.3/lwjgl-glfw-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-glfw/3.2.3/lwjgl-glfw-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-glfw/3.2.3/lwjgl-glfw-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.jawt",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-jawt/3.2.3/lwjgl-jawt-3.2.3.jar");
    put(
        "org.lwjgl.jemalloc",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-jemalloc/3.2.3/lwjgl-jemalloc-3.2.3.jar");
    put(
        "org.lwjgl.jemalloc.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-jemalloc/3.2.3/lwjgl-jemalloc-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-jemalloc/3.2.3/lwjgl-jemalloc-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-jemalloc/3.2.3/lwjgl-jemalloc-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.libdivide",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-libdivide/3.2.3/lwjgl-libdivide-3.2.3.jar");
    put(
        "org.lwjgl.libdivide.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-libdivide/3.2.3/lwjgl-libdivide-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-libdivide/3.2.3/lwjgl-libdivide-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-libdivide/3.2.3/lwjgl-libdivide-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.llvm",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-llvm/3.2.3/lwjgl-llvm-3.2.3.jar");
    put(
        "org.lwjgl.llvm.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-llvm/3.2.3/lwjgl-llvm-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-llvm/3.2.3/lwjgl-llvm-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-llvm/3.2.3/lwjgl-llvm-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.lmdb",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lmdb/3.2.3/lwjgl-lmdb-3.2.3.jar");
    put(
        "org.lwjgl.lmdb.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lmdb/3.2.3/lwjgl-lmdb-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lmdb/3.2.3/lwjgl-lmdb-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lmdb/3.2.3/lwjgl-lmdb-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.lz4",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lz4/3.2.3/lwjgl-lz4-3.2.3.jar");
    put(
        "org.lwjgl.lz4.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lz4/3.2.3/lwjgl-lz4-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lz4/3.2.3/lwjgl-lz4-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-lz4/3.2.3/lwjgl-lz4-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.meow",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-meow/3.2.3/lwjgl-meow-3.2.3.jar");
    put(
        "org.lwjgl.meow.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-meow/3.2.3/lwjgl-meow-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-meow/3.2.3/lwjgl-meow-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-meow/3.2.3/lwjgl-meow-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.nanovg",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nanovg/3.2.3/lwjgl-nanovg-3.2.3.jar");
    put(
        "org.lwjgl.nanovg.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nanovg/3.2.3/lwjgl-nanovg-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nanovg/3.2.3/lwjgl-nanovg-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nanovg/3.2.3/lwjgl-nanovg-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl/3.2.3/lwjgl-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.nfd",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nfd/3.2.3/lwjgl-nfd-3.2.3.jar");
    put(
        "org.lwjgl.nfd.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nfd/3.2.3/lwjgl-nfd-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nfd/3.2.3/lwjgl-nfd-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nfd/3.2.3/lwjgl-nfd-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.nuklear",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nuklear/3.2.3/lwjgl-nuklear-3.2.3.jar");
    put(
        "org.lwjgl.nuklear.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nuklear/3.2.3/lwjgl-nuklear-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nuklear/3.2.3/lwjgl-nuklear-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nuklear/3.2.3/lwjgl-nuklear-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.odbc",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-odbc/3.2.3/lwjgl-odbc-3.2.3.jar");
    put(
        "org.lwjgl.openal",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openal/3.2.3/lwjgl-openal-3.2.3.jar");
    put(
        "org.lwjgl.openal.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openal/3.2.3/lwjgl-openal-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openal/3.2.3/lwjgl-openal-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openal/3.2.3/lwjgl-openal-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.opencl",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opencl/3.2.3/lwjgl-opencl-3.2.3.jar");
    put(
        "org.lwjgl.opengl",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3.jar");
    put(
        "org.lwjgl.opengl.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengl/3.2.3/lwjgl-opengl-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.opengles",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengles/3.2.3/lwjgl-opengles-3.2.3.jar");
    put(
        "org.lwjgl.opengles.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengles/3.2.3/lwjgl-opengles-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengles/3.2.3/lwjgl-opengles-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opengles/3.2.3/lwjgl-opengles-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.openvr",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openvr/3.2.3/lwjgl-openvr-3.2.3.jar");
    put(
        "org.lwjgl.openvr.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openvr/3.2.3/lwjgl-openvr-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openvr/3.2.3/lwjgl-openvr-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-openvr/3.2.3/lwjgl-openvr-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.opus",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opus/3.2.3/lwjgl-opus-3.2.3.jar");
    put(
        "org.lwjgl.opus.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opus/3.2.3/lwjgl-opus-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opus/3.2.3/lwjgl-opus-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-opus/3.2.3/lwjgl-opus-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.ovr",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-ovr/3.2.3/lwjgl-ovr-3.2.3.jar");
    put(
        "org.lwjgl.par",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-par/3.2.3/lwjgl-par-3.2.3.jar");
    put(
        "org.lwjgl.par.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-par/3.2.3/lwjgl-par-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-par/3.2.3/lwjgl-par-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-par/3.2.3/lwjgl-par-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.remotery",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-remotery/3.2.3/lwjgl-remotery-3.2.3.jar");
    put(
        "org.lwjgl.remotery.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-remotery/3.2.3/lwjgl-remotery-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-remotery/3.2.3/lwjgl-remotery-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-remotery/3.2.3/lwjgl-remotery-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.rpmalloc",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-rpmalloc/3.2.3/lwjgl-rpmalloc-3.2.3.jar");
    put(
        "org.lwjgl.rpmalloc.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-rpmalloc/3.2.3/lwjgl-rpmalloc-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-rpmalloc/3.2.3/lwjgl-rpmalloc-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-rpmalloc/3.2.3/lwjgl-rpmalloc-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.shaderc",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-shaderc/3.2.3/lwjgl-shaderc-3.2.3.jar");
    put(
        "org.lwjgl.shaderc.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-shaderc/3.2.3/lwjgl-shaderc-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-shaderc/3.2.3/lwjgl-shaderc-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-shaderc/3.2.3/lwjgl-shaderc-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.sse",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-sse/3.2.3/lwjgl-sse-3.2.3.jar");
    put(
        "org.lwjgl.sse.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-sse/3.2.3/lwjgl-sse-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-sse/3.2.3/lwjgl-sse-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-sse/3.2.3/lwjgl-sse-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.stb",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-stb/3.2.3/lwjgl-stb-3.2.3.jar");
    put(
        "org.lwjgl.stb.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-stb/3.2.3/lwjgl-stb-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-stb/3.2.3/lwjgl-stb-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-stb/3.2.3/lwjgl-stb-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.tinyexr",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyexr/3.2.3/lwjgl-tinyexr-3.2.3.jar");
    put(
        "org.lwjgl.tinyexr.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyexr/3.2.3/lwjgl-tinyexr-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyexr/3.2.3/lwjgl-tinyexr-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyexr/3.2.3/lwjgl-tinyexr-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.tinyfd",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyfd/3.2.3/lwjgl-tinyfd-3.2.3.jar");
    put(
        "org.lwjgl.tinyfd.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyfd/3.2.3/lwjgl-tinyfd-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyfd/3.2.3/lwjgl-tinyfd-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tinyfd/3.2.3/lwjgl-tinyfd-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.tootle",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tootle/3.2.3/lwjgl-tootle-3.2.3.jar");
    put(
        "org.lwjgl.tootle.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tootle/3.2.3/lwjgl-tootle-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tootle/3.2.3/lwjgl-tootle-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-tootle/3.2.3/lwjgl-tootle-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.vma",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vma/3.2.3/lwjgl-vma-3.2.3.jar");
    put(
        "org.lwjgl.vma.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vma/3.2.3/lwjgl-vma-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vma/3.2.3/lwjgl-vma-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vma/3.2.3/lwjgl-vma-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.vulkan",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vulkan/3.2.3/lwjgl-vulkan-3.2.3.jar");
    put(
        "org.lwjgl.xxhash",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-xxhash/3.2.3/lwjgl-xxhash-3.2.3.jar");
    put(
        "org.lwjgl.xxhash.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-xxhash/3.2.3/lwjgl-xxhash-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-xxhash/3.2.3/lwjgl-xxhash-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-xxhash/3.2.3/lwjgl-xxhash-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.yoga",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-yoga/3.2.3/lwjgl-yoga-3.2.3.jar");
    put(
        "org.lwjgl.yoga.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-yoga/3.2.3/lwjgl-yoga-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-yoga/3.2.3/lwjgl-yoga-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-yoga/3.2.3/lwjgl-yoga-3.2.3-natives-windows.jar"));
    put(
        "org.lwjgl.zstd",
        "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-zstd/3.2.3/lwjgl-zstd-3.2.3.jar");
    put(
        "org.lwjgl.zstd.natives",
        platform(
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-zstd/3.2.3/lwjgl-zstd-3.2.3-natives-linux.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-zstd/3.2.3/lwjgl-zstd-3.2.3-natives-macos.jar",
            "https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-zstd/3.2.3/lwjgl-zstd-3.2.3-natives-windows.jar"));
    put(
        "org.objectweb.asm",
        "https://repo.maven.apache.org/maven2/org/ow2/asm/asm/8.0.1/asm-8.0.1.jar");
    put(
        "org.objectweb.asm.commons",
        "https://repo.maven.apache.org/maven2/org/ow2/asm/asm-commons/8.0.1/asm-commons-8.0.1.jar");
    put(
        "org.objectweb.asm.tree",
        "https://repo.maven.apache.org/maven2/org/ow2/asm/asm-tree/8.0.1/asm-tree-8.0.1.jar");
    put(
        "org.objectweb.asm.tree.analysis",
        "https://repo.maven.apache.org/maven2/org/ow2/asm/asm-analysis/8.0.1/asm-analysis-8.0.1.jar");
    put(
        "org.objectweb.asm.util",
        "https://repo.maven.apache.org/maven2/org/ow2/asm/asm-util/8.0.1/asm-util-8.0.1.jar");
    put(
        "org.opentest4j",
        "https://repo.maven.apache.org/maven2/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar");
  }
}
