name: 'Update install-jdk.properties'
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Because...'
  schedule:
    - cron: '23 */4 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - name: 'Check out sources'
        uses: actions/checkout@v2
        with:
          ref: master
      - name: 'Show JDK builds published at https://jdk.java.net'
        run: |
          "${JAVA_HOME_11_X64}/bin/java" src/bach/ShowJdkBuilds.java > install-jdk.properties
          cat install-jdk.properties
      - name: 'Check for modifications'
        id: diff
        run: |
          git diff
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo 'false'; else echo 'true'; fi)
      - name: 'Commit and push changed install-jdk.properties'
        if: steps.diff.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --message 'Update install-jdk.properties' install-jdk.properties
          git push
